# Form implementation generated from reading ui file 'd:\22753\duwenba\note\py\untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        Frame.resize(277, 112)
        Frame.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        Frame.setAutoFillBackground(False)
        Frame.setStyleSheet("#Frame {\n"
"    background: #666;\n"
"}")
        Frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Frame)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.label.setFont(font)
        self.label.setStyleSheet("#lable_2 {\n"
"     font-family: \'CristoLIkid Tryout\';\n"
"     font-size: 20px;\n"
"     font-weight: 900;\n"
"     color: #ffffff;\n"
"    font: 900 36pt \"Segoe UI Black\";\n"
"    background: #fff;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "<html><head/><body><p>12:09</p><p><br/></p></body></html>"))
        self.label_2.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-family:\'Comic Sans MS\'; font-size:15pt; font-weight:700; color:#ffffff;\">TextLabel</span></p></body></html>"))
